[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "anthropic>=0.50.0",
    "faiss-cpu>=1.11.0",
    "langchain-anthropic>=0.3.12",
    "langchain>=0.3.24",
    "langchain-core>=0.3.56",
    "langchain-openai>=0.3.14",
    "openai>=1.76.0",
    "streamlit>=1.44.1",
    "sqlalchemy>=2.0.40",
    "psycopg2-binary>=2.9.10",
    "groq>=0.23.1",
    "langchain-groq>=0.3.2",
]
